prefix: "&7[&aJustAnimations&7] &r"

messages:
  reload: "Reloading Config..."
  reload-error: "Error while reloading config!"
  reload-success: "Config reloaded!"
  create: "Creating new animation..."
  create-error: "Error while creating animation!"
  create-success: "Animation created!"
  create-exists: "An animation with this name already exists!"
  delete: "Deleting animation..."
  delete-error: "Error while deleting animation!"
  delete-success: "Animation '%animation%' deleted!"
  delete-not-exists: "Animation '%animation%' does not exist!"
  animation-not-exists: "Animation does not exist!"
  help: "Type /justanimations help to see a list of available commands."
  toggle-reverse: "Toggled reverse mode for animation '%animation%' to %value%!"
  world-change: "Changed world for animation '%animation%' to %value%!"
  world-not-exists: "World '%value%' does not exist!"
  world-in-use: "World '%value%' is already in use by this animation!"
  settings: "Settings for animation '%animation%':"
  getframe: "Current frame is %value%"
  addframe: "Added frame %value% to animation '%animation%'!"
  addframe-error: "Error while adding frame %value% to animation '%animation%'!"
  play-animation: "Playing animation '%animation%'!"
  play-animation-running: "Animation '%animation%' is already running!"
  play-animation-error: "Error while playing animation '%animation%'!"
  play-animation-empty: "The animation '%animation%' does not have any frames to play"
  stop-animation: "Stopped animation '%animation%'!"
  stop-animation-not-running: "Animation '%animation%' is not running!"
  stop-animation-error: "Error while stopping animation '%animation%'!"
  go-to-frame: "Frame set to %value% for animation '%animation%'!"
  go-to-frame-error: "Error while setting frame to %value% for animation '%animation%'!"
  go-to-frame-not-exists: "Frame %value% does not exist for animation '%animation%'!"
  converting: "Converting animation '%animation%' to '%value%'..."
  converting-error: "Error while converting animation '%animation%' to '%value%'!"
  converting-success: "Converted animation '%animation%' to '%value%'!"
  frame-selection-success: "Your region selection is now frame %value% of animation '%animation%'!"
  frame-selection-error: "Error while setting your region selection to frame %value% of animation '%animation%'"
  setload: "Set load type for animation '%animation%' to %value%!"
  setload-error: "Error while setting load type for animation '%animation%' to %value%!"
  setload-success: "Load type for animation '%animation%' set to %value%!"
  setload-already-set: "Load type for animation '%animation%' is already set to %value%!"
  random-error: "Error while randomizing frames for animation '%animation%'!"
  random-success: "Toggled randomized frames for animation '%animation%' to %value%!"
  rename-success: "Renamed animation '%animation%' to '%value%'!"
  rename-error: "Error while renaming animation '%animation%' to '%value%'!"
  rename-exists: "An animation with this name already exists!"
  rename-no-value: "You must specify a new name for the animation!"
  remove: "Please specify a frame to remove!"
  remove-success: "Removed frame %value% from animation '%animation%'!"
  remove-error: "Error while removing frame %value% from animation '%animation%'!"
  remove-not-exists: "Frame %value% does not exist for animation '%animation%'!"

settings:
